apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-meta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-meta
  template:
    metadata:
      labels:
        app: supabase-meta
    spec:
      containers:
        - name: supabase-meta
          image: supabase/postgres-meta:v0.80.0
          ports:
            - containerPort: 8080
          env:
            - name: PG_META_PORT
              value: "8080"
            - name: PG_META_DB_HOST
              value: supabase-postgres-service
            - name: PG_META_DB_PORT
              value: "5432"
            - name: PG_META_DB_NAME
              value: postgres
            - name: PG_META_DB_USER
              value: supabase_admin
            - name: PG_META_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-db
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: supabase-meta-service
spec:
  selector:
    app: supabase-meta
  ports:
    - protocol: TCP
      port: 8080
