apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-realtime
  template:
    metadata:
      labels:
        app: supabase-realtime
    spec:
      containers:
        - name: supabase-realtime
          image: supabase/realtime:v2.28.32
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "/app/bin/migrate && /app/bin/realtime eval 'Realtime.Release.seeds(Realtime.Repo)' && /app/bin/server",
            ]
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: DB_HOST
              value: supabase-postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: supabase_admin
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-db
                  key: password
            - name: DB_NAME
              value: postgres
            - name: DB_AFTER_CONNECT_QUERY
              value: "SET search_path TO _realtime"
            - name: DB_ENC_KEY
              value: supabaserealtime
            - name: API_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-jwt
                  key: secret
            - name: FLY_ALLOC_ID
              value: fly123
            - name: FLY_APP_NAME
              value: realtime
            - name: SECRET_KEY_BASE
              value: UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8etQoXz3gZv1/u2oq
            - name: ERL_AFLAGS
              value: -proto_dist inet_tcp
            - name: ENABLE_TAILSCALE
              value: "false"
            - name: DNS_NODES
              value: "''"
---
apiVersion: v1
kind: Service
metadata:
  name: supabase-realtime-service
spec:
  selector:
    app: supabase-realtime
  ports:
    - protocol: TCP
      port: 4000
