apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-kong
  template:
    metadata:
      labels:
        app: supabase-kong
    spec:
      containers:
        - name: supabase-kong
          image: kong:2.8.1
          command: ["/bin/sh"]
          args: ["/scripts/wrapper.sh"]
          ports:
            - containerPort: 8000
            - containerPort: 8443
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /home/kong/kong.yml
              # https://github.com/supabase/cli/issues/14
            - name: KONG_DNS_ORDER
              value: LAST,A,CNAME
            - name: KONG_PLUGINS
              value: request-transformer,cors,key-auth,acl,basic-auth
            - name: KONG_NGINX_PROXY_PROXY_BUFFER_SIZE
              value: 160k
            - name: KONG_NGINX_PROXY_PROXY_BUFFERS
              value: 64 160k

            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-jwt
                  key: anonKey
            - name: SUPABASE_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-jwt
                  key: serviceKey

              # username/password to access dashboard
            - name: DASHBOARD_USERNAME
              valueFrom:
                secretKeyRef:
                  name: supabase-kong
                  key: username
            - name: DASHBOARD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-kong
                  key: password

          volumeMounts:
            - name: config
              mountPath: /home/kong/temp.yml
              subPath: temp.yml
            - name: wrapper
              mountPath: /scripts/

      volumes:
        - name: config
          configMap:
            name: supabase-kong
            defaultMode: 0644
            items:
              - key: kong-conf.yaml
                path: temp.yml
        - name: wrapper
          configMap:
            name: supabase-kong
            defaultMode: 0755
            items:
              - key: kong-wrapper.sh
                path: wrapper.sh
